name: KICS-scan
on: [push, pull_request]

jobs:
  KICS-scan:
    name: KICS-scan
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Mkdir results-dir
        # make sure results dir is created
        run: mkdir -p results-dir
      # Scan Iac with kics
      - name: run kics Scan
        uses: checkmarx/kics-github-action@latest
        with:
          path: 'terraform'
          output_path: results-dir
      # Display the results in json format
      - name: display kics results
        run: |
          cat results-dir/results.json
        # optionally parse the results with jq
        # jq '.total_counter' results-dir/results.json
        # jq '.queries_total' results-dir/results.json
